name: Build, Push, and Deploy Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.event.commits[0].sha }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Deploy Docker image to EC2 instance
        uses: bitovi/github-actions-deploy-docker-to-ec2@v2
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.event.commits[0].sha }}
          ec2_instance_id: ${{ secrets.EC2_HOST }}
          ec2_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
